name: 'Test GUS Regon API'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['7.2', '7.3', '7.4', '8.0', '8.1']
        phpunit-versions: ['latest']
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: soap
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: composer

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: 'Install composer dependencies'
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader

      - name: 'Run tests'
        run: |
          ./vendor/bin/phpunit tests/

      - name: 'Coding standard PHP 7.2'
        if: ${{ matrix.php-versions == '7.2' }}
        run: |
          ./vendor/bin/ecs check

